// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znvkxhzlghprahvaolze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpudmt4aHpsZ2hwcmFodmFvbHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMDYwODEsImV4cCI6MjA1MjY4MjA4MX0.rseSILzQyOS0OfgZ8Cci8qI6bp30aHVRoV64dRFd9jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);