// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmzvukqdsnmtzsneuhxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtenZ1a3Fkc25tdHpzbmV1aHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NzE4ODQsImV4cCI6MjA1NTU0Nzg4NH0.mdLYBAoLQPc9q2dYs1SQhfPFciIpj9KtyERj9g13iho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);